name: starreviews
description: A flutter package for displaying detailed star reviews
version: 1.0.5
homepage: https://github.com/buraktabn/starreviews

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  percent_indicator: "^2.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: